version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
    - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - app-network
    deploy:
      placement:
        constraints:
          - node.role == manager 

  backend:
    image: 192.168.1.106:5000/be:latest
    ports:
      - "3003:3003"
    environment:
      DB_HOST: database  
      DB_PORT: 5432
      DB_NAME: spotify
      DB_USER: local
      DB_PASSWORD: local
      NODE_ENV: production
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager 
    depends_on:
      - database

  frontend:
    image: 192.168.1.106:5000/fe:latest
    ports :
      - "5173:5173"
    environment:
      - VITE_API_URL=http://192.168.1.106:3003
    networks:
      - app-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker  

networks:
  app-network:
    driver: overlay

volumes:
  db_data:
    driver: local